### ISSUE TITLE
Spotify authentication fails on deployed app

### ISSUE THREAD

**Issue by kmthorsnes** [CraftAcademy/CraftOverflow#24]
## Problem
We have successfully managed to have users log in on our app using their spotify-account on our localhost, but when we try to log in on our deployed app we redirected to a page saying: 
"We're sorry, but something went wrong."

### Background
We want to set up spotify log in on our app. 
We have already added the key and secret for spotify in our heruku settings, and we have included the redirect URI in our spotify developer account settings (see screenshots)

#### Story

```
As a user
In order to be able to make account easily
I would like to log in using my spotify account.
```
#### Error from heruko application log
```
2018-03-03T12:28:47.392772+00:00 app[web.1]: -                      c.collname, col_description(a.attrelid, a.attnum) AS comment
2018-03-03T12:28:47.392778+00:00 app[web.1]: -                 LEFT JOIN pg_type t ON a.atttypid = t.oid
2018-03-03T12:28:47.392780+00:00 app[web.1]: -                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
2018-03-03T12:28:47.392784+00:00 app[web.1]: -                  AND a.attnum > 0 AND NOT a.attisdropped
2018-03-03T12:28:47.392785+00:00 app[web.1]: -                ORDER BY a.attnum
2018-03-03T12:28:47.392782+00:00 app[web.1]: -                WHERE a.attrelid = '"users"'::regclass
2018-03-03T12:28:47.392787+00:00 app[web.1]: - ):
2018-03-03T12:28:47.392792+00:00 app[web.1]: - F, [2018-03-03T12:28:47.392758 #4] FATAL -- : [ff243ac0-7e9c-49f1-9bf4-724f08324fff]   
2018-03-03T12:28:47.392848+00:00 app[web.1]: - F, [2018-03-03T12:28:47.392800 #4] FATAL -- : [ff243ac0-7e9c-49f1-9bf4-724f08324fff] app/models/user.rb:9:in `from_omniauth'
2018-03-03T12:28:47.392851+00:00 app[web.1]: - [ff243ac0-7e9c-49f1-9bf4-724f08324fff] app/controllers/omniauth_callbacks_controller.rb:4:in `spotify'
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2018-03-03T12:28:47.392772+00:00 app[web.1]: -                      c.collname, col_description(a.attrelid, a.attnum) AS comment
2018-03-03T12:28:47.392778+00:00 app[web.1]: -                 LEFT JOIN pg_type t ON a.atttypid = t.oid
2018-03-03T12:28:47.392780+00:00 app[web.1]: -                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
2018-03-03T12:28:47.392784+00:00 app[web.1]: -                  AND a.attnum > 0 AND NOT a.attisdropped
2018-03-03T12:28:47.392785+00:00 app[web.1]: -                ORDER BY a.attnum
2018-03-03T12:28:47.392782+00:00 app[web.1]: -                WHERE a.attrelid = '"users"'::regclass
2018-03-03T12:28:47.392787+00:00 app[web.1]: - ):
2018-03-03T12:28:47.392792+00:00 app[web.1]: - F, [2018-03-03T12:28:47.392758 #4] FATAL -- : [ff243ac0-7e9c-49f1-9bf4-724f08324fff]   
2018-03-03T12:28:47.392848+00:00 app[web.1]: - F, [2018-03-03T12:28:47.392800 #4] FATAL -- : [ff243ac0-7e9c-49f1-9bf4-724f08324fff] app/models/user.rb:9:in `from_omniauth'
2018-03-03T12:28:47.392851+00:00 app[web.1]: - [ff243ac0-7e9c-49f1-9bf4-724f08324fff] app/controllers/omniauth_callbacks_controller.rb:4:in `spotify'
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2018-03-03T12:28:47.392772+00:00 app[web.1]: -                      c.collname, col_description(a.attrelid, a.attnum) AS comment
2018-03-03T12:28:47.392778+00:00 app[web.1]: -                 LEFT JOIN pg_type t ON a.atttypid = t.oid
2018-03-03T12:28:47.392780+00:00 app[web.1]: -                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
2018-03-03T12:28:47.392784+00:00 app[web.1]: -                  AND a.attnum > 0 AND NOT a.attisdropped
2018-03-03T12:28:47.392785+00:00 app[web.1]: -                ORDER BY a.attnum
2018-03-03T12:28:47.392782+00:00 app[web.1]: -                WHERE a.attrelid = '"users"'::regclass
2018-03-03T12:28:47.392787+00:00 app[web.1]: - ):
2018-03-03T12:28:47.392792+00:00 app[web.1]: - F, [2018-03-03T12:28:47.392758 #4] FATAL -- : [ff243ac0-7e9c-49f1-9bf4-724f08324fff]   
2018-03-03T12:28:47.392848+00:00 app[web.1]: - F, [2018-03-03T12:28:47.392800 #4] FATAL -- : [ff243ac0-7e9c-49f1-9bf4-724f08324fff] app/models/user.rb:9:in `from_omniauth'
2018-03-03T12:28:47.392851+00:00 app[web.1]: - [ff243ac0-7e9c-49f1-9bf4-724f08324fff] app/controllers/omniauth_callbacks_controller.rb:4:in `spotify'
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2018-03-03T12:28:47.392772+00:00 app[web.1]: -                      c.collname, col_description(a.attrelid, a.attnum) AS comment
2018-03-03T12:28:47.392778+00:00 app[web.1]: -                 LEFT JOIN pg_type t ON a.atttypid = t.oid
2018-03-03T12:28:47.392780+00:00 app[web.1]: -                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
2018-03-03T12:28:47.392784+00:00 app[web.1]: -                  AND a.attnum > 0 AND NOT a.attisdropped
2018-03-03T12:28:47.392785+00:00 app[web.1]: -                ORDER BY a.attnum
2018-03-03T12:28:47.392782+00:00 app[web.1]: -                WHERE a.attrelid = '"users"'::regclass
2018-03-03T12:28:47.392787+00:00 app[web.1]: - ):
2018-03-03T12:28:47.392792+00:00 app[web.1]: - F, [2018-03-03T12:28:47.392758 #4] FATAL -- : [ff243ac0-7e9c-49f1-9bf4-724f08324fff]   
2018-03-03T12:28:47.392848+00:00 app[web.1]: - F, [2018-03-03T12:28:47.392800 #4] FATAL -- : [ff243ac0-7e9c-49f1-9bf4-724f08324fff] app/models/user.rb:9:in `from_omniauth'
2018-03-03T12:28:47.392851+00:00 app[web.1]: - [ff243ac0-7e9c-49f1-9bf4-724f08324fff] app/controllers/omniauth_callbacks_controller.rb:4:in `spotify'
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2018-03-03T12:28:47.392772+00:00 app[web.1]: -                      c.collname, col_description(a.attrelid, a.attnum) AS comment
2018-03-03T12:28:47.392778+00:00 app[web.1]: -                 LEFT JOIN pg_type t ON a.atttypid = t.oid
2018-03-03T12:28:47.392780+00:00 app[web.1]: -                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
2018-03-03T12:28:47.392784+00:00 app[web.1]: -                  AND a.attnum > 0 AND NOT a.attisdropped
2018-03-03T12:28:47.392785+00:00 app[web.1]: -                ORDER BY a.attnum
2018-03-03T12:28:47.392782+00:00 app[web.1]: -                WHERE a.attrelid = '"users"'::regclass
2018-03-03T12:28:47.392787+00:00 app[web.1]: - ):
2018-03-03T12:28:47.392792+00:00 app[web.1]: - F, [2018-03-03T12:28:47.392758 #4] FATAL -- : [ff243ac0-7e9c-49f1-9bf4-724f08324fff]   
2018-03-03T12:28:47.392848+00:00 app[web.1]: - F, [2018-03-03T12:28:47.392800 #4] FATAL -- : [ff243ac0-7e9c-49f1-9bf4-724f08324fff] app/models/user.rb:9:in `from_omniauth'
2018-03-03T12:28:47.392851+00:00 app[web.1]: - [ff243ac0-7e9c-49f1-9bf4-724f08324fff] app/controllers/omniauth_callbacks_controller.rb:4:in `spotify'
Disconnected from log stream. There may be events happening that you do not see here! Attempting to reconnect...
2018-03-03T12:28:47.392772+00:00 app[web.1]: -                      c.collname, col_description(a.attrelid, a.attnum) AS comment
2018-03-03T12:28:47.392778+00:00 app[web.1]: -                 LEFT JOIN pg_type t ON a.atttypid = t.oid
2018-03-03T12:28:47.392780+00:00 app[web.1]: -                 LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
2018-03-03T12:28:47.392784+00:00 app[web.1]: -                  AND a.attnum > 0 AND NOT a.attisdropped
2018-03-03T12:28:47.392785+00:00 app[web.1]: -                ORDER BY a.attnum
2018-03-03T12:28:47.392782+00:00 app[web.1]: -                WHERE a.attrelid = '"users"'::regclass
2018-03-03T12:28:47.392787+00:00 app[web.1]: - ):
2018-03-03T12:28:47.392792+00:00 app[web.1]: - F, [2018-03-03T12:28:47.392758 #4] FATAL -- : [ff243ac0-7e9c-49f1-9bf4-724f08324fff]   
2018-03-03T12:28:47.392848+00:00 app[web.1]: - F, [2018-03-03T12:28:47.392800 #4] FATAL -- : [ff243ac0-7e9c-49f1-9bf4-724f08324fff] app/models/user.rb:9:in `from_omniauth'
2018-03-03T12:28:47.392851+00:00 app[web.1]: - [ff243ac0-7e9c-49f1-9bf4-724f08324fff] app/controllers/omniauth_callbacks_controller.rb:4:in `spotify'
```

### Screenshots
<img width="785" alt="skjermbilde 2018-03-03 kl 13 13 37" src="https://user-images.githubusercontent.com/24756550/36934379-dab5fe98-1ee8-11e8-8389-7d6ba2120ffa.png">
<img width="1650" alt="skjermbilde 2018-03-03 kl 13 22 46" src="https://user-images.githubusercontent.com/24756550/36934381-de8a8804-1ee8-11e8-897e-e5973ad8b7f8.png">
<img width="1481" alt="skjermbilde 2018-03-03 kl 13 23 01" src="https://user-images.githubusercontent.com/24756550/36934386-e23fb32a-1ee8-11e8-9055-0685ef122060.png">
<img width="17" alt="skjermbilde 2018-03-03 kl 13 30 14" src="https://user-images.githubusercontent.com/24756550/36934388-e7442a40-1ee8-11e8-9add-a13ca9f16c24.png">
<img width="1287" alt="skjermbilde 2018-03-03 kl 13 13 47" src="https://user-images.githubusercontent.com/24756550/36934380-dc7a3032-1ee8-11e8-9bdc-9b0c36cb6984.png">
<img width="1226" alt="skjermbilde 2018-03-03 kl 13 30 36" src="https://user-images.githubusercontent.com/24756550/36934392-efb3133a-1ee8-11e8-9262-5c5f350f87ae.png">

### How did you try to solve the problem?
- We have tried to use different callback URLs, but no change. 
- We have also tried to have a closer look at the files which the logs tells us the errors are happening, without figuring out why it fails (app/models/user.rb:9 and app/controllers/omniauth_callbacks_controller.rb:4) 
- We found this post on StackOverflow: https://stackoverflow.com/questions/32983926/spotify-omniauth which indicates that there might be some issues when using both devise and omniauth. Can this be the case for us too? 

###
Markdown [guide](https://guides.github.com/features/mastering-markdown/)

**Comment by tochman** [comment]
Please run your migrations on Heroku.

**Comment by kmthorsnes** [comment]
To run the migrations solved the issue
```
$ heroku login
```
Then logged in using our credentials.
After that, the following line. 
```
$ heroku run rake db:migrate --app euphonyapp
```
