### ISSUE TITLE
JSONapi - RSpec - uninitialized constant RSpec (NameError)

### ISSUE THREAD

**Issue by holgertidemand** [CraftAcademy/CraftOverflow#26]
## Problem
Our Cucumber test is not working after we installed jsonapi-rspec gem. 
We keep getting 
``` 
uninitialized constant RSpec (NameError)
/Users/holgertidemand/.rvm/gems/ruby-2.4.1@rails_5_2/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
/Users/holgertidemand/.rvm/gems/ruby-2.4.1@rails_5_2/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:8:in `without_bootsnap_cache'
/Users/holgertidemand/.rvm/gems/ruby-2.4.1@rails_5_2/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `rescue in load_missing_constant'
/Users/holgertidemand/.rvm/gems/ruby-2.4.1@rails_5_2/gems/bootsnap-1.2.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:43:in `load_missing_constant'
/Users/holgertidemand/.rvm/gems/ruby-2.4.1@rails_5_2/gems/jsonapi-rspec-0.0.2/lib/jsonapi/rspec/id.rb:4:in `<module:Id>'
/Users/holgertidemand/.rvm/gems/ruby-2.4.1@rails_5_2/gems/jsonapi-rspec-0.0.2/lib/jsonapi/rspec/id.rb:3:in `<module:RSpec>'
/Users/holgertidemand/.rvm/gems/ruby-2.4.1@rails_5_2/gems/jsonapi-rspec-0.0.2/lib/jsonapi/rspec/id.rb:2:in `<module:JSONAPI>'
/Users/holgertidemand/.rvm/gems/ruby-2.4.1@rails_5_2/gems/jsonapi-rspec-0.0.2/lib/jsonapi/rspec/id.rb:1:in `<top (required)>'
``` 

### Background
We installed the gem and made our test pass, server is working fine, but our cucumber test are not working. 

#### Implementation code

rails_helper.rb
```
  RSpec.configure do |config|
  [...]
  config.include JSONAPI::RSpec
end
```
Gemfile
 ```
gem 'rack-cors', require: 'rack/cors'
gem 'active_model_serializers', '~> 0.10.0'

group :test do
  gem 'jsonapi-rspec'
end

 ```

**Comment by tochman** [comment]
Please show me the entire `rails_helper.rb` I think there's an error in the configuration block.

**Comment by Fleurtam** [comment]
```
require 'spec_helper'
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'rspec/rails'

ActiveRecord::Migration.maintain_test_schema!
Dir[Rails.root.join('spec/support/**/*.rb')].each { |f| require f }

RSpec.configure do |config|
  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.use_transactional_fixtures = true
  config.infer_spec_type_from_file_location!
  config.filter_rails_from_backtrace!
  config.include FactoryBot::Syntax::Methods
  config.include JSONAPI::RSpec
end

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end
```

**Comment by Fleurtam** [comment]
Problem solved by setting the requirement to false in the gemfile
```
  gem 'jsonapi-rspec', require: false
```
and then requiring it specifically in the rails-helper file
```
require 'jsonapi/rspec'
```

**Comment by tochman** [comment]
This was a bit tricky. Seems like there's a problem with JsonapiRspec playing nicely with Cucumber. The solution is to use the following setting:

Gemfile:
```
group :test do
  gem 'jsonapi-rspec', require: false
end
```

And the then, in `rails_helper.rb` make sure to add:
```
require 'jsonapi/rpec
```
And you should be ready to go.
